export type pokeTypes =  {
    fire: string,
    grass: string,
    electric: string,
    water: string,
    ground: string,
    rock: string,
    fairy: string,
    poison: string,
    bug: string,
    dragon: string,
    psychic: string,
    flying: string,
    fighting: string,
    normal: string,
    ghost: string,
    steel: string,
    ice: string,
    dark: string,
}
export const colorsForType:pokeTypes  = {
    fire: "#f08030",
    grass: "#78c850",
    electric: "#f8d030",
    water: "#a890f0",
    ground: "#e0c068",
    rock: "#b8a038",
    fairy: "#ee99ac",
    poison: "#a040a0",
    bug: "#a8b820",
    dragon: "#7038f8",
    psychic: "#f85888",
    flying: "#a890f0",
    fighting: "#c02038",
    normal: "#a8a878",
    ghost: "#705898",
    steel: "#b8b8d0",
    ice: "#98d8d8",
    dark: "#705848",
} 

